### ISSUE TITLE
Keep getting this error with 4.11

### ISSUE THREAD

**Issue by muzaheed57** [RyroNZ/UE4MasterServer#6] opened 2016-08-19 05:15 UTC
Keep getting this error with 4.11

Error	13	error LNK2019: unresolved external symbol 
"__declspec(dllimport) public: static class TBaseDelegate<class FFixedUObjectArray *> & __cdecl FCoreDelegates::GetObjectArrayForDebugVisualizersDelegate(void)" 

(__imp_?GetObjectArrayForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAVFFixedUObjectArray@@$$$V@@XZ) 
referenced in function 
"void __cdecl `dynamic initializer for 'GObjectArrayForDebugVisualizers''(void)" (??__EGObjectArrayForDebugVisualizers@@YAXXZ)	H:\UnrealProjects\StarImperium_2\Intermediate\ProjectFiles\Module.MasterServer.cpp.obj

Is there a version for 4.11?

**Comment by muzaheed57** [comment] 2016-08-19 11:23
fixed by compiling with 4.12.5

**Comment by RyroNZ** [comment] 2016-09-01 23:28
Not sure what the issue is looking at that I've been able to compile and use right up to 4.12.5 as I keep my project on the latest version... I'll close this off anyway.

**Closed by RyroNZ** 2016-09-01 23:28 UTC
